package com.proyectofinal.datos.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.proyectofinal.datos.dao.CategoriaProductoDAO;
import com.proyectofinal.datos.domain.CategoriaProducto;
import com.proyectofinal.datos.dto.CategoriaProductoExample;

public class CategoriaProductoDAOImpl extends SqlMapClientDaoSupport implements CategoriaProductoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public CategoriaProductoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int countByExample(CategoriaProductoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"categoria_productos.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int deleteByPrimaryKey(Integer idCategoriaProductos) {
		CategoriaProducto key = new CategoriaProducto();
		key.setIdCategoriaProductos(idCategoriaProductos);
		int rows = getSqlMapClientTemplate().delete(
				"categoria_productos.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public Integer insert(CategoriaProducto record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"categoria_productos.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public Integer insertSelective(CategoriaProducto record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"categoria_productos.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	@SuppressWarnings("unchecked")
	public List<CategoriaProducto> selectByExample(
			CategoriaProductoExample example) {
		List<CategoriaProducto> list = getSqlMapClientTemplate().queryForList(
				"categoria_productos.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public CategoriaProducto selectByPrimaryKey(Integer idCategoriaProductos) {
		CategoriaProducto key = new CategoriaProducto();
		key.setIdCategoriaProductos(idCategoriaProductos);
		CategoriaProducto record = (CategoriaProducto) getSqlMapClientTemplate()
				.queryForObject(
						"categoria_productos.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int updateByExampleSelective(CategoriaProducto record,
			CategoriaProductoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"categoria_productos.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int updateByExample(CategoriaProducto record,
			CategoriaProductoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"categoria_productos.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int updateByPrimaryKeySelective(CategoriaProducto record) {
		int rows = getSqlMapClientTemplate()
				.update("categoria_productos.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int updateByPrimaryKey(CategoriaProducto record) {
		int rows = getSqlMapClientTemplate().update(
				"categoria_productos.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private static class UpdateByExampleParms extends CategoriaProductoExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				CategoriaProductoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}