package com.proyectofinal.datos.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.proyectofinal.datos.dao.ClienteDAO;
import com.proyectofinal.datos.domain.Cliente;
import com.proyectofinal.datos.dto.ClienteExample;

public class ClienteDAOImpl extends SqlMapClientDaoSupport implements ClienteDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public ClienteDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public int countByExample(ClienteExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("clientes.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public int deleteByPrimaryKey(Integer idCliente) {
        Cliente key = new Cliente();
        key.setIdCliente(idCliente);
        int rows = getSqlMapClientTemplate().delete("clientes.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public Integer insert(Cliente record) {
        Object newKey = getSqlMapClientTemplate().insert("clientes.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public Integer insertSelective(Cliente record) {
        Object newKey = getSqlMapClientTemplate().insert("clientes.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<Cliente> selectByExample(ClienteExample example) {
        List<Cliente> list = getSqlMapClientTemplate().queryForList("clientes.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public Cliente selectByPrimaryKey(Integer idCliente) {
        Cliente key = new Cliente();
        key.setIdCliente(idCliente);
        Cliente record = (Cliente) getSqlMapClientTemplate().queryForObject("clientes.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public int updateByPrimaryKeySelective(Cliente record) {
        int rows = getSqlMapClientTemplate().update("clientes.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public int updateByPrimaryKey(Cliente record) {
        int rows = getSqlMapClientTemplate().update("clientes.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}