package com.proyectofinal.datos.dao.impl;


import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.proyectofinal.datos.dao.EstadoPedidoDAO;
import com.proyectofinal.datos.domain.EstadoPedido;
import com.proyectofinal.datos.dto.EstadoPedidoExample;

public class EstadoPedidoDAOImpl extends SqlMapClientDaoSupport implements EstadoPedidoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public EstadoPedidoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int countByExample(EstadoPedidoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"estado_pedidos.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int deleteByPrimaryKey(Integer idEstadoPedido) {
		EstadoPedido key = new EstadoPedido();
		key.setIdEstadoPedido(idEstadoPedido);
		int rows = getSqlMapClientTemplate().delete(
				"estado_pedidos.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public Integer insert(EstadoPedido record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"estado_pedidos.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public Integer insertSelective(EstadoPedido record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"estado_pedidos.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	@SuppressWarnings("unchecked")
	public List<EstadoPedido> selectByExample(EstadoPedidoExample example) {
		List<EstadoPedido> list = getSqlMapClientTemplate().queryForList(
				"estado_pedidos.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public EstadoPedido selectByPrimaryKey(Integer idEstadoPedido) {
		EstadoPedido key = new EstadoPedido();
		key.setIdEstadoPedido(idEstadoPedido);
		EstadoPedido record = (EstadoPedido) getSqlMapClientTemplate()
				.queryForObject(
						"estado_pedidos.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int updateByExampleSelective(EstadoPedido record,
			EstadoPedidoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"estado_pedidos.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int updateByExample(EstadoPedido record, EstadoPedidoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"estado_pedidos.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int updateByPrimaryKeySelective(EstadoPedido record) {
		int rows = getSqlMapClientTemplate().update(
				"estado_pedidos.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int updateByPrimaryKey(EstadoPedido record) {
		int rows = getSqlMapClientTemplate().update(
				"estado_pedidos.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private static class UpdateByExampleParms extends EstadoPedidoExample {
		private Object record;

		public UpdateByExampleParms(Object record, EstadoPedidoExample example) {
			super(example);
			this.record = record;
		}

		@SuppressWarnings("unused")
		public Object getRecord() {
			return record;
		}
	}
}