package com.proyectofinal.datos.dao.impl;


import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.proyectofinal.datos.dao.EstadoProductoDAO;
import com.proyectofinal.datos.domain.EstadoProducto;
import com.proyectofinal.datos.dto.EstadoProductoExample;

public class EstadoProductoDAOImpl extends SqlMapClientDaoSupport implements EstadoProductoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public EstadoProductoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int countByExample(EstadoProductoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"estado_productos.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int deleteByPrimaryKey(Integer idEstadoProducto) {
		EstadoProducto key = new EstadoProducto();
		key.setIdEstadoProducto(idEstadoProducto);
		int rows = getSqlMapClientTemplate().delete(
				"estado_productos.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public Integer insert(EstadoProducto record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"estado_productos.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public Integer insertSelective(EstadoProducto record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"estado_productos.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	@SuppressWarnings("unchecked")
	public List<EstadoProducto> selectByExample(EstadoProductoExample example) {
		List<EstadoProducto> list = getSqlMapClientTemplate().queryForList(
				"estado_productos.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public EstadoProducto selectByPrimaryKey(Integer idEstadoProducto) {
		EstadoProducto key = new EstadoProducto();
		key.setIdEstadoProducto(idEstadoProducto);
		EstadoProducto record = (EstadoProducto) getSqlMapClientTemplate()
				.queryForObject(
						"estado_productos.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int updateByExampleSelective(EstadoProducto record,
			EstadoProductoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"estado_productos.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int updateByExample(EstadoProducto record,
			EstadoProductoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"estado_productos.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int updateByPrimaryKeySelective(EstadoProducto record) {
		int rows = getSqlMapClientTemplate().update(
				"estado_productos.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public int updateByPrimaryKey(EstadoProducto record) {
		int rows = getSqlMapClientTemplate().update(
				"estado_productos.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table estado_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private static class UpdateByExampleParms extends EstadoProductoExample {
		private Object record;

		public UpdateByExampleParms(Object record, EstadoProductoExample example) {
			super(example);
			this.record = record;
		}

		@SuppressWarnings("unused")
		public Object getRecord() {
			return record;
		}
	}
}