package com.proyectofinal.datos.dao.impl;

import com.proyectofinal.datos.dao.FacturaDAO;
import com.proyectofinal.datos.domain.Factura;
import com.proyectofinal.datos.dto.FacturaExample;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class FacturaDAOImpl extends SqlMapClientDaoSupport implements FacturaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table facturas
     *
     * @ibatorgenerated Thu Oct 22 16:39:02 CDT 2015
     */
    public FacturaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table facturas
     *
     * @ibatorgenerated Thu Oct 22 16:39:02 CDT 2015
     */
    public int countByExample(FacturaExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("facturas.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table facturas
     *
     * @ibatorgenerated Thu Oct 22 16:39:02 CDT 2015
     */
    public int deleteByPrimaryKey(Integer idFactura) {
        Factura key = new Factura();
        key.setIdFactura(idFactura);
        int rows = getSqlMapClientTemplate().delete("facturas.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table facturas
     *
     * @ibatorgenerated Thu Oct 22 16:39:02 CDT 2015
     */
    public Integer insert(Factura record) {
        Object newKey = getSqlMapClientTemplate().insert("facturas.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table facturas
     *
     * @ibatorgenerated Thu Oct 22 16:39:02 CDT 2015
     */
    public Integer insertSelective(Factura record) {
        Object newKey = getSqlMapClientTemplate().insert("facturas.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table facturas
     *
     * @ibatorgenerated Thu Oct 22 16:39:02 CDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<Factura> selectByExample(FacturaExample example) {
        List<Factura> list = getSqlMapClientTemplate().queryForList("facturas.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table facturas
     *
     * @ibatorgenerated Thu Oct 22 16:39:02 CDT 2015
     */
    public Factura selectByPrimaryKey(Integer idFactura) {
        Factura key = new Factura();
        key.setIdFactura(idFactura);
        Factura record = (Factura) getSqlMapClientTemplate().queryForObject("facturas.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table facturas
     *
     * @ibatorgenerated Thu Oct 22 16:39:02 CDT 2015
     */
    public int updateByExampleSelective(Factura record, FacturaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("facturas.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table facturas
     *
     * @ibatorgenerated Thu Oct 22 16:39:02 CDT 2015
     */
    public int updateByExample(Factura record, FacturaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("facturas.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table facturas
     *
     * @ibatorgenerated Thu Oct 22 16:39:02 CDT 2015
     */
    public int updateByPrimaryKeySelective(Factura record) {
        int rows = getSqlMapClientTemplate().update("facturas.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table facturas
     *
     * @ibatorgenerated Thu Oct 22 16:39:02 CDT 2015
     */
    public int updateByPrimaryKey(Factura record) {
        int rows = getSqlMapClientTemplate().update("facturas.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table facturas
     *
     * @ibatorgenerated Thu Oct 22 16:39:02 CDT 2015
     */
    private static class UpdateByExampleParms extends FacturaExample {
        private Object record;

        public UpdateByExampleParms(Object record, FacturaExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }
}