package com.proyectofinal.datos.dao.impl;

import com.proyectofinal.datos.dao.InstanciaProductoDAO;
import com.proyectofinal.datos.domain.InstanciaProducto;
import com.proyectofinal.datos.dto.InstanciaProductoExample;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class InstanciaProductoDAOImpl extends SqlMapClientDaoSupport implements InstanciaProductoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public InstanciaProductoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public int countByExample(InstanciaProductoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("instancia_productos.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public int deleteByPrimaryKey(Integer idInstanciaProducto) {
        InstanciaProducto key = new InstanciaProducto();
        key.setIdInstanciaProducto(idInstanciaProducto);
        int rows = getSqlMapClientTemplate().delete("instancia_productos.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public Integer insert(InstanciaProducto record) {
        Object newKey = getSqlMapClientTemplate().insert("instancia_productos.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public Integer insertSelective(InstanciaProducto record) {
        Object newKey = getSqlMapClientTemplate().insert("instancia_productos.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<InstanciaProducto> selectByExample(InstanciaProductoExample example) {
        List<InstanciaProducto> list = getSqlMapClientTemplate().queryForList("instancia_productos.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public InstanciaProducto selectByPrimaryKey(Integer idInstanciaProducto) {
        InstanciaProducto key = new InstanciaProducto();
        key.setIdInstanciaProducto(idInstanciaProducto);
        InstanciaProducto record = (InstanciaProducto) getSqlMapClientTemplate().queryForObject("instancia_productos.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public int updateByExampleSelective(InstanciaProducto record, InstanciaProductoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("instancia_productos.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public int updateByExample(InstanciaProducto record, InstanciaProductoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("instancia_productos.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public int updateByPrimaryKeySelective(InstanciaProducto record) {
        int rows = getSqlMapClientTemplate().update("instancia_productos.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public int updateByPrimaryKey(InstanciaProducto record) {
        int rows = getSqlMapClientTemplate().update("instancia_productos.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    private static class UpdateByExampleParms extends InstanciaProductoExample {
        private Object record;

        public UpdateByExampleParms(Object record, InstanciaProductoExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }
}