package com.proyectofinal.datos.dao.impl;

import com.proyectofinal.datos.dao.PagosDAO;
import com.proyectofinal.datos.domain.Pagos;
import com.proyectofinal.datos.dto.PagosExample;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PagosDAOImpl extends SqlMapClientDaoSupport implements PagosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pagos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public PagosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pagos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public int countByExample(PagosExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pagos.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pagos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public int deleteByPrimaryKey(Integer idPago) {
        Pagos key = new Pagos();
        key.setIdPago(idPago);
        int rows = getSqlMapClientTemplate().delete("pagos.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pagos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public Integer insert(Pagos record) {
        Object newKey = getSqlMapClientTemplate().insert("pagos.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pagos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public Integer insertSelective(Pagos record) {
        Object newKey = getSqlMapClientTemplate().insert("pagos.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pagos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<Pagos> selectByExample(PagosExample example) {
        List<Pagos> list = getSqlMapClientTemplate().queryForList("pagos.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pagos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public Pagos selectByPrimaryKey(Integer idPago) {
        Pagos key = new Pagos();
        key.setIdPago(idPago);
        Pagos record = (Pagos) getSqlMapClientTemplate().queryForObject("pagos.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pagos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public int updateByExampleSelective(Pagos record, PagosExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pagos.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pagos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public int updateByExample(Pagos record, PagosExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pagos.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pagos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public int updateByPrimaryKeySelective(Pagos record) {
        int rows = getSqlMapClientTemplate().update("pagos.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pagos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public int updateByPrimaryKey(Pagos record) {
        int rows = getSqlMapClientTemplate().update("pagos.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pagos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    private static class UpdateByExampleParms extends PagosExample {
        private Object record;

        public UpdateByExampleParms(Object record, PagosExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }
}