package com.proyectofinal.datos.dao.impl;

import com.proyectofinal.datos.dao.PedidoDAO;
import com.proyectofinal.datos.domain.Pedido;
import com.proyectofinal.datos.dto.PedidoExample;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PedidoDAOImpl extends SqlMapClientDaoSupport implements PedidoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public PedidoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public int countByExample(PedidoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pedidos.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public int deleteByPrimaryKey(Integer idPedido) {
        Pedido key = new Pedido();
        key.setIdPedido(idPedido);
        int rows = getSqlMapClientTemplate().delete("pedidos.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public Integer insert(Pedido record) {
        Object newKey = getSqlMapClientTemplate().insert("pedidos.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public Integer insertSelective(Pedido record) {
        Object newKey = getSqlMapClientTemplate().insert("pedidos.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<Pedido> selectByExample(PedidoExample example) {
        List<Pedido> list = getSqlMapClientTemplate().queryForList("pedidos.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public Pedido selectByPrimaryKey(Integer idPedido) {
        Pedido key = new Pedido();
        key.setIdPedido(idPedido);
        Pedido record = (Pedido) getSqlMapClientTemplate().queryForObject("pedidos.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public int updateByExampleSelective(Pedido record, PedidoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pedidos.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public int updateByExample(Pedido record, PedidoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pedidos.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public int updateByPrimaryKeySelective(Pedido record) {
        int rows = getSqlMapClientTemplate().update("pedidos.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public int updateByPrimaryKey(Pedido record) {
        int rows = getSqlMapClientTemplate().update("pedidos.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    private static class UpdateByExampleParms extends PedidoExample {
        private Object record;

        public UpdateByExampleParms(Object record, PedidoExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }
}