package com.proyectofinal.datos.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.proyectofinal.datos.dao.ProductoDAO;
import com.proyectofinal.datos.domain.Producto;
import com.proyectofinal.datos.dto.ProductoExample;

public class ProductoDAOImpl extends SqlMapClientDaoSupport implements ProductoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public ProductoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public int countByExample(ProductoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("productos.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public int deleteByPrimaryKey(Integer idProducto) {
        Producto key = new Producto();
        key.setIdProducto(idProducto);
        int rows = getSqlMapClientTemplate().delete("productos.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public Integer insert(Producto record) {
        Object newKey = getSqlMapClientTemplate().insert("productos.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public Integer insertSelective(Producto record) {
        Object newKey = getSqlMapClientTemplate().insert("productos.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<Producto> selectByExample(ProductoExample example) {
        List<Producto> list = getSqlMapClientTemplate().queryForList("productos.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public Producto selectByPrimaryKey(Integer idProducto) {
        Producto key = new Producto();
        key.setIdProducto(idProducto);
        Producto record = (Producto) getSqlMapClientTemplate().queryForObject("productos.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public int updateByPrimaryKeySelective(Producto record) {
        int rows = getSqlMapClientTemplate().update("productos.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public int updateByPrimaryKey(Producto record) {
        int rows = getSqlMapClientTemplate().update("productos.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}