package com.proyectofinal.datos.dao.impl;

import com.proyectofinal.datos.dao.TipoPagoDAO;
import com.proyectofinal.datos.domain.TipoPago;
import com.proyectofinal.datos.dto.TipoPagoExample;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TipoPagoDAOImpl extends SqlMapClientDaoSupport implements TipoPagoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public TipoPagoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public int countByExample(TipoPagoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tipos_pago.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public int deleteByPrimaryKey(Integer idTipoPago) {
        TipoPago key = new TipoPago();
        key.setIdTipoPago(idTipoPago);
        int rows = getSqlMapClientTemplate().delete("tipos_pago.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public Integer insert(TipoPago record) {
        Object newKey = getSqlMapClientTemplate().insert("tipos_pago.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public Integer insertSelective(TipoPago record) {
        Object newKey = getSqlMapClientTemplate().insert("tipos_pago.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<TipoPago> selectByExample(TipoPagoExample example) {
        List<TipoPago> list = getSqlMapClientTemplate().queryForList("tipos_pago.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public TipoPago selectByPrimaryKey(Integer idTipoPago) {
        TipoPago key = new TipoPago();
        key.setIdTipoPago(idTipoPago);
        TipoPago record = (TipoPago) getSqlMapClientTemplate().queryForObject("tipos_pago.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public int updateByExampleSelective(TipoPago record, TipoPagoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tipos_pago.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public int updateByExample(TipoPago record, TipoPagoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tipos_pago.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public int updateByPrimaryKeySelective(TipoPago record) {
        int rows = getSqlMapClientTemplate().update("tipos_pago.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public int updateByPrimaryKey(TipoPago record) {
        int rows = getSqlMapClientTemplate().update("tipos_pago.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    private static class UpdateByExampleParms extends TipoPagoExample {
        private Object record;

        public UpdateByExampleParms(Object record, TipoPagoExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }
}