package com.proyectofinal.datos.dao.impl;

import com.proyectofinal.datos.dao.TipoEntregaDAO;
import com.proyectofinal.datos.domain.TipoEntrega;
import com.proyectofinal.datos.dto.TipoEntregaExample;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TipoEntregaDAOImpl extends SqlMapClientDaoSupport implements TipoEntregaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public TipoEntregaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public int countByExample(TipoEntregaExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tipo_entrega.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public int deleteByPrimaryKey(Integer idTipoEntrega) {
        TipoEntrega key = new TipoEntrega();
        key.setIdTipoEntrega(idTipoEntrega);
        int rows = getSqlMapClientTemplate().delete("tipo_entrega.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public Integer insert(TipoEntrega record) {
        Object newKey = getSqlMapClientTemplate().insert("tipo_entrega.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public Integer insertSelective(TipoEntrega record) {
        Object newKey = getSqlMapClientTemplate().insert("tipo_entrega.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<TipoEntrega> selectByExample(TipoEntregaExample example) {
        List<TipoEntrega> list = getSqlMapClientTemplate().queryForList("tipo_entrega.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public TipoEntrega selectByPrimaryKey(Integer idTipoEntrega) {
        TipoEntrega key = new TipoEntrega();
        key.setIdTipoEntrega(idTipoEntrega);
        TipoEntrega record = (TipoEntrega) getSqlMapClientTemplate().queryForObject("tipo_entrega.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public int updateByExampleSelective(TipoEntrega record, TipoEntregaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tipo_entrega.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public int updateByExample(TipoEntrega record, TipoEntregaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tipo_entrega.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public int updateByPrimaryKeySelective(TipoEntrega record) {
        int rows = getSqlMapClientTemplate().update("tipo_entrega.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public int updateByPrimaryKey(TipoEntrega record) {
        int rows = getSqlMapClientTemplate().update("tipo_entrega.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    private static class UpdateByExampleParms extends TipoEntregaExample {
        private Object record;

        public UpdateByExampleParms(Object record, TipoEntregaExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }
}