package com.proyectofinal.datos.domain;

public class CategoriaProducto {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column categoria_productos.id_categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private Integer idCategoriaProductos;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column categoria_productos.nombre
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column categoria_productos.descripcion
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private String descripcion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column categoria_productos.id_categoria_productos
	 * @return  the value of categoria_productos.id_categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public Integer getIdCategoriaProductos() {
		return idCategoriaProductos;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column categoria_productos.id_categoria_productos
	 * @param idCategoriaProductos  the value for categoria_productos.id_categoria_productos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public void setIdCategoriaProductos(Integer idCategoriaProductos) {
		this.idCategoriaProductos = idCategoriaProductos;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column categoria_productos.nombre
	 * @return  the value of categoria_productos.nombre
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column categoria_productos.nombre
	 * @param nombre  the value for categoria_productos.nombre
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column categoria_productos.descripcion
	 * @return  the value of categoria_productos.descripcion
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column categoria_productos.descripcion
	 * @param descripcion  the value for categoria_productos.descripcion
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}