package com.proyectofinal.datos.domain;

public class Cliente {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column clientes.id_cliente
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private Integer idCliente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column clientes.nombre
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private String nombre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column clientes.apellido_paterno
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private String apellido_paterno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column clientes.apellido_materno
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private String apellido_materno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column clientes.email
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column clientes.nombre_usuario
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private String nombre_usuario;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column clientes.contrasena
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private String contrasena;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column clientes.imagen
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private String imagen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column clientes.id_rol
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private Long id_rol;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column clientes.id_cliente
     *
     * @return the value of clientes.id_cliente
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public Integer getIdCliente() {
        return idCliente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column clientes.id_cliente
     *
     * @param idCliente the value for clientes.id_cliente
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column clientes.nombre
     *
     * @return the value of clientes.nombre
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column clientes.nombre
     *
     * @param nombre the value for clientes.nombre
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column clientes.apellido_paterno
     *
     * @return the value of clientes.apellido_paterno
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getApellido_paterno() {
        return apellido_paterno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column clientes.apellido_paterno
     *
     * @param apellido_paterno the value for clientes.apellido_paterno
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setApellido_paterno(String apellido_paterno) {
        this.apellido_paterno = apellido_paterno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column clientes.apellido_materno
     *
     * @return the value of clientes.apellido_materno
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getApellido_materno() {
        return apellido_materno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column clientes.apellido_materno
     *
     * @param apellido_materno the value for clientes.apellido_materno
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setApellido_materno(String apellido_materno) {
        this.apellido_materno = apellido_materno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column clientes.email
     *
     * @return the value of clientes.email
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column clientes.email
     *
     * @param email the value for clientes.email
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column clientes.nombre_usuario
     *
     * @return the value of clientes.nombre_usuario
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getNombre_usuario() {
        return nombre_usuario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column clientes.nombre_usuario
     *
     * @param nombre_usuario the value for clientes.nombre_usuario
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setNombre_usuario(String nombre_usuario) {
        this.nombre_usuario = nombre_usuario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column clientes.contrasena
     *
     * @return the value of clientes.contrasena
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getContrasena() {
        return contrasena;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column clientes.contrasena
     *
     * @param contrasena the value for clientes.contrasena
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column clientes.imagen
     *
     * @return the value of clientes.imagen
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getImagen() {
        return imagen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column clientes.imagen
     *
     * @param imagen the value for clientes.imagen
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column clientes.id_rol
     *
     * @return the value of clientes.id_rol
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public Long getId_rol() {
        return id_rol;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column clientes.id_rol
     *
     * @param id_rol the value for clientes.id_rol
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setId_rol(Long id_rol) {
        this.id_rol = id_rol;
    }
}