package com.proyectofinal.datos.domain;

import java.util.Date;

public class Entrega {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column entrega.id_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    private Integer idEntrega;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column entrega.id_pedido
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    private Long id_pedido;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column entrega.fecha_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    private Date fecha_entrega;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column entrega.POD
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    private String POD;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column entrega.comentarios
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    private String comentarios;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column entrega.id_tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    private Long id_tipo_entrega;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column entrega.id_entrega
     *
     * @return the value of entrega.id_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public Integer getIdEntrega() {
        return idEntrega;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column entrega.id_entrega
     *
     * @param idEntrega the value for entrega.id_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public void setIdEntrega(Integer idEntrega) {
        this.idEntrega = idEntrega;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column entrega.id_pedido
     *
     * @return the value of entrega.id_pedido
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public Long getId_pedido() {
        return id_pedido;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column entrega.id_pedido
     *
     * @param id_pedido the value for entrega.id_pedido
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public void setId_pedido(Long id_pedido) {
        this.id_pedido = id_pedido;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column entrega.fecha_entrega
     *
     * @return the value of entrega.fecha_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public Date getFecha_entrega() {
        return fecha_entrega;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column entrega.fecha_entrega
     *
     * @param fecha_entrega the value for entrega.fecha_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public void setFecha_entrega(Date fecha_entrega) {
        this.fecha_entrega = fecha_entrega;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column entrega.POD
     *
     * @return the value of entrega.POD
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public String getPOD() {
        return POD;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column entrega.POD
     *
     * @param POD the value for entrega.POD
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public void setPOD(String POD) {
        this.POD = POD;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column entrega.comentarios
     *
     * @return the value of entrega.comentarios
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public String getComentarios() {
        return comentarios;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column entrega.comentarios
     *
     * @param comentarios the value for entrega.comentarios
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column entrega.id_tipo_entrega
     *
     * @return the value of entrega.id_tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public Long getId_tipo_entrega() {
        return id_tipo_entrega;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column entrega.id_tipo_entrega
     *
     * @param id_tipo_entrega the value for entrega.id_tipo_entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public void setId_tipo_entrega(Long id_tipo_entrega) {
        this.id_tipo_entrega = id_tipo_entrega;
    }
}