package com.proyectofinal.datos.domain;

public class EstadoPedido {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column estado_pedidos.id_estado_pedido
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private Integer idEstadoPedido;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column estado_pedidos.nombre
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column estado_pedidos.descripcion
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private String descripcion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column estado_pedidos.id_estado_pedido
	 * @return  the value of estado_pedidos.id_estado_pedido
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public Integer getIdEstadoPedido() {
		return idEstadoPedido;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column estado_pedidos.id_estado_pedido
	 * @param idEstadoPedido  the value for estado_pedidos.id_estado_pedido
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public void setIdEstadoPedido(Integer idEstadoPedido) {
		this.idEstadoPedido = idEstadoPedido;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column estado_pedidos.nombre
	 * @return  the value of estado_pedidos.nombre
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column estado_pedidos.nombre
	 * @param nombre  the value for estado_pedidos.nombre
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column estado_pedidos.descripcion
	 * @return  the value of estado_pedidos.descripcion
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column estado_pedidos.descripcion
	 * @param descripcion  the value for estado_pedidos.descripcion
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}