package com.proyectofinal.datos.domain;

public class EstadoProducto {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column estado_productos.id_estado_producto
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private Integer idEstadoProducto;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column estado_productos.nombre
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column estado_productos.descripcion
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private String descripcion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column estado_productos.id_estado_producto
	 * @return  the value of estado_productos.id_estado_producto
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public Integer getIdEstadoProducto() {
		return idEstadoProducto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column estado_productos.id_estado_producto
	 * @param idEstadoProducto  the value for estado_productos.id_estado_producto
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public void setIdEstadoProducto(Integer idEstadoProducto) {
		this.idEstadoProducto = idEstadoProducto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column estado_productos.nombre
	 * @return  the value of estado_productos.nombre
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column estado_productos.nombre
	 * @param nombre  the value for estado_productos.nombre
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column estado_productos.descripcion
	 * @return  the value of estado_productos.descripcion
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column estado_productos.descripcion
	 * @param descripcion  the value for estado_productos.descripcion
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}