package com.proyectofinal.datos.domain;

import java.util.Date;

public class Factura {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column facturas.id_factura
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	private Integer idFactura;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column facturas.id_pedido
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	private Long id_pedido;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column facturas.RFC_cliente
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	private String RFC_cliente;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column facturas.fecha_emision
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	private Date fecha_emision;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column facturas.id_factura
	 * @return  the value of facturas.id_factura
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	public Integer getIdFactura() {
		return idFactura;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column facturas.id_factura
	 * @param idFactura  the value for facturas.id_factura
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	public void setIdFactura(Integer idFactura) {
		this.idFactura = idFactura;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column facturas.id_pedido
	 * @return  the value of facturas.id_pedido
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	public Long getId_pedido() {
		return id_pedido;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column facturas.id_pedido
	 * @param id_pedido  the value for facturas.id_pedido
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	public void setId_pedido(Long id_pedido) {
		this.id_pedido = id_pedido;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column facturas.RFC_cliente
	 * @return  the value of facturas.RFC_cliente
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	public String getRFC_cliente() {
		return RFC_cliente;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column facturas.RFC_cliente
	 * @param RFC_cliente  the value for facturas.RFC_cliente
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	public void setRFC_cliente(String RFC_cliente) {
		this.RFC_cliente = RFC_cliente;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column facturas.fecha_emision
	 * @return  the value of facturas.fecha_emision
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	public Date getFecha_emision() {
		return fecha_emision;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column facturas.fecha_emision
	 * @param fecha_emision  the value for facturas.fecha_emision
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	public void setFecha_emision(Date fecha_emision) {
		this.fecha_emision = fecha_emision;
	}
}