package com.proyectofinal.datos.domain;

import java.util.Date;

public class InstanciaProducto {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column instancia_productos.id_instancia_producto
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    private Integer idInstanciaProducto;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column instancia_productos.codigo
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    private String codigo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column instancia_productos.fecha_recibido
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    private Date fecha_recibido;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column instancia_productos.id_producto
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    private Long id_producto;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column instancia_productos.id_estado_producto
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    private Long id_estado_producto;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column instancia_productos.id_instancia_producto
     *
     * @return the value of instancia_productos.id_instancia_producto
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public Integer getIdInstanciaProducto() {
        return idInstanciaProducto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column instancia_productos.id_instancia_producto
     *
     * @param idInstanciaProducto the value for instancia_productos.id_instancia_producto
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public void setIdInstanciaProducto(Integer idInstanciaProducto) {
        this.idInstanciaProducto = idInstanciaProducto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column instancia_productos.codigo
     *
     * @return the value of instancia_productos.codigo
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column instancia_productos.codigo
     *
     * @param codigo the value for instancia_productos.codigo
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column instancia_productos.fecha_recibido
     *
     * @return the value of instancia_productos.fecha_recibido
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public Date getFecha_recibido() {
        return fecha_recibido;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column instancia_productos.fecha_recibido
     *
     * @param fecha_recibido the value for instancia_productos.fecha_recibido
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public void setFecha_recibido(Date fecha_recibido) {
        this.fecha_recibido = fecha_recibido;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column instancia_productos.id_producto
     *
     * @return the value of instancia_productos.id_producto
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public Long getId_producto() {
        return id_producto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column instancia_productos.id_producto
     *
     * @param id_producto the value for instancia_productos.id_producto
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public void setId_producto(Long id_producto) {
        this.id_producto = id_producto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column instancia_productos.id_estado_producto
     *
     * @return the value of instancia_productos.id_estado_producto
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public Long getId_estado_producto() {
        return id_estado_producto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column instancia_productos.id_estado_producto
     *
     * @param id_estado_producto the value for instancia_productos.id_estado_producto
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    public void setId_estado_producto(Long id_estado_producto) {
        this.id_estado_producto = id_estado_producto;
    }
}