package com.proyectofinal.datos.domain;

public class Pagos {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pagos.id_pago
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    private Integer idPago;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pagos.id_pedido
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    private Long id_pedido;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pagos.id_tipo_pago
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    private Long id_tipo_pago;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pagos.id_pago
     *
     * @return the value of pagos.id_pago
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public Integer getIdPago() {
        return idPago;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pagos.id_pago
     *
     * @param idPago the value for pagos.id_pago
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public void setIdPago(Integer idPago) {
        this.idPago = idPago;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pagos.id_pedido
     *
     * @return the value of pagos.id_pedido
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public Long getId_pedido() {
        return id_pedido;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pagos.id_pedido
     *
     * @param id_pedido the value for pagos.id_pedido
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public void setId_pedido(Long id_pedido) {
        this.id_pedido = id_pedido;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pagos.id_tipo_pago
     *
     * @return the value of pagos.id_tipo_pago
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public Long getId_tipo_pago() {
        return id_tipo_pago;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pagos.id_tipo_pago
     *
     * @param id_tipo_pago the value for pagos.id_tipo_pago
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public void setId_tipo_pago(Long id_tipo_pago) {
        this.id_tipo_pago = id_tipo_pago;
    }
}