package com.proyectofinal.datos.domain;

import java.util.Date;

public class Pedido {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pedidos.id_pedido
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    private Integer idPedido;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pedidos.id_cliente
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    private Long id_cliente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pedidos.fecha_pedido
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    private Date fecha_pedido;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pedidos.id_estado_pedido
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    private Long id_estado_pedido;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pedidos.id_pedido
     *
     * @return the value of pedidos.id_pedido
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public Integer getIdPedido() {
        return idPedido;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pedidos.id_pedido
     *
     * @param idPedido the value for pedidos.id_pedido
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pedidos.id_cliente
     *
     * @return the value of pedidos.id_cliente
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public Long getId_cliente() {
        return id_cliente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pedidos.id_cliente
     *
     * @param id_cliente the value for pedidos.id_cliente
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public void setId_cliente(Long id_cliente) {
        this.id_cliente = id_cliente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pedidos.fecha_pedido
     *
     * @return the value of pedidos.fecha_pedido
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public Date getFecha_pedido() {
        return fecha_pedido;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pedidos.fecha_pedido
     *
     * @param fecha_pedido the value for pedidos.fecha_pedido
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public void setFecha_pedido(Date fecha_pedido) {
        this.fecha_pedido = fecha_pedido;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pedidos.id_estado_pedido
     *
     * @return the value of pedidos.id_estado_pedido
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public Long getId_estado_pedido() {
        return id_estado_pedido;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pedidos.id_estado_pedido
     *
     * @param id_estado_pedido the value for pedidos.id_estado_pedido
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    public void setId_estado_pedido(Long id_estado_pedido) {
        this.id_estado_pedido = id_estado_pedido;
    }
}