package com.proyectofinal.datos.domain;

public class Producto {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column productos.id_producto
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private Integer idProducto;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column productos.nombre
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private String nombre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column productos.descripcion
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private String descripcion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column productos.codigo
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private String codigo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column productos.imagen
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private String imagen;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column productos.imagen_1
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private String imagen_1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column productos.imagen_2
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private String imagen_2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column productos.precio
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    private Double precio;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column productos.id_producto
     *
     * @return the value of productos.id_producto
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public Integer getIdProducto() {
        return idProducto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column productos.id_producto
     *
     * @param idProducto the value for productos.id_producto
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column productos.nombre
     *
     * @return the value of productos.nombre
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column productos.nombre
     *
     * @param nombre the value for productos.nombre
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column productos.descripcion
     *
     * @return the value of productos.descripcion
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column productos.descripcion
     *
     * @param descripcion the value for productos.descripcion
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column productos.codigo
     *
     * @return the value of productos.codigo
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column productos.codigo
     *
     * @param codigo the value for productos.codigo
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column productos.imagen
     *
     * @return the value of productos.imagen
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getImagen() {
        return imagen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column productos.imagen
     *
     * @param imagen the value for productos.imagen
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column productos.imagen_1
     *
     * @return the value of productos.imagen_1
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getImagen_1() {
        return imagen_1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column productos.imagen_1
     *
     * @param imagen_1 the value for productos.imagen_1
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setImagen_1(String imagen_1) {
        this.imagen_1 = imagen_1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column productos.imagen_2
     *
     * @return the value of productos.imagen_2
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getImagen_2() {
        return imagen_2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column productos.imagen_2
     *
     * @param imagen_2 the value for productos.imagen_2
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setImagen_2(String imagen_2) {
        this.imagen_2 = imagen_2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column productos.precio
     *
     * @return the value of productos.precio
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public Double getPrecio() {
        return precio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column productos.precio
     *
     * @param precio the value for productos.precio
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
}