package com.proyectofinal.datos.domain;

public class TipoEntrega {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tipo_entrega.id_tipo_entrega
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private Integer idTipoEntrega;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tipo_entrega.nombre
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tipo_entrega.descripcion
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	private String descripcion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tipo_entrega.id_tipo_entrega
	 * @return  the value of tipo_entrega.id_tipo_entrega
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public Integer getIdTipoEntrega() {
		return idTipoEntrega;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tipo_entrega.id_tipo_entrega
	 * @param idTipoEntrega  the value for tipo_entrega.id_tipo_entrega
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public void setIdTipoEntrega(Integer idTipoEntrega) {
		this.idTipoEntrega = idTipoEntrega;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tipo_entrega.nombre
	 * @return  the value of tipo_entrega.nombre
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tipo_entrega.nombre
	 * @param nombre  the value for tipo_entrega.nombre
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tipo_entrega.descripcion
	 * @return  the value of tipo_entrega.descripcion
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tipo_entrega.descripcion
	 * @param descripcion  the value for tipo_entrega.descripcion
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}