package com.proyectofinal.datos.domain;

public class TipoPago {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tipos_pago.id_tipo_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    private Integer idTipoPago;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tipos_pago.nombre
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    private String nombre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tipos_pago.descripcion
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    private String descripcion;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tipos_pago.id_tipo_pago
     *
     * @return the value of tipos_pago.id_tipo_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public Integer getIdTipoPago() {
        return idTipoPago;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tipos_pago.id_tipo_pago
     *
     * @param idTipoPago the value for tipos_pago.id_tipo_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public void setIdTipoPago(Integer idTipoPago) {
        this.idTipoPago = idTipoPago;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tipos_pago.nombre
     *
     * @return the value of tipos_pago.nombre
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tipos_pago.nombre
     *
     * @param nombre the value for tipos_pago.nombre
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tipos_pago.descripcion
     *
     * @return the value of tipos_pago.descripcion
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tipos_pago.descripcion
     *
     * @param descripcion the value for tipos_pago.descripcion
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}