package com.proyectofinal.datos.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EntregaExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public EntregaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    protected EntregaExample(EntregaExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdEntregaIsNull() {
            addCriterion("id_entrega is null");
            return this;
        }

        public Criteria andIdEntregaIsNotNull() {
            addCriterion("id_entrega is not null");
            return this;
        }

        public Criteria andIdEntregaEqualTo(Integer value) {
            addCriterion("id_entrega =", value, "idEntrega");
            return this;
        }

        public Criteria andIdEntregaNotEqualTo(Integer value) {
            addCriterion("id_entrega <>", value, "idEntrega");
            return this;
        }

        public Criteria andIdEntregaGreaterThan(Integer value) {
            addCriterion("id_entrega >", value, "idEntrega");
            return this;
        }

        public Criteria andIdEntregaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_entrega >=", value, "idEntrega");
            return this;
        }

        public Criteria andIdEntregaLessThan(Integer value) {
            addCriterion("id_entrega <", value, "idEntrega");
            return this;
        }

        public Criteria andIdEntregaLessThanOrEqualTo(Integer value) {
            addCriterion("id_entrega <=", value, "idEntrega");
            return this;
        }

        public Criteria andIdEntregaIn(List<Integer> values) {
            addCriterion("id_entrega in", values, "idEntrega");
            return this;
        }

        public Criteria andIdEntregaNotIn(List<Integer> values) {
            addCriterion("id_entrega not in", values, "idEntrega");
            return this;
        }

        public Criteria andIdEntregaBetween(Integer value1, Integer value2) {
            addCriterion("id_entrega between", value1, value2, "idEntrega");
            return this;
        }

        public Criteria andIdEntregaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_entrega not between", value1, value2, "idEntrega");
            return this;
        }

        public Criteria andId_pedidoIsNull() {
            addCriterion("id_pedido is null");
            return this;
        }

        public Criteria andId_pedidoIsNotNull() {
            addCriterion("id_pedido is not null");
            return this;
        }

        public Criteria andId_pedidoEqualTo(Long value) {
            addCriterion("id_pedido =", value, "id_pedido");
            return this;
        }

        public Criteria andId_pedidoNotEqualTo(Long value) {
            addCriterion("id_pedido <>", value, "id_pedido");
            return this;
        }

        public Criteria andId_pedidoGreaterThan(Long value) {
            addCriterion("id_pedido >", value, "id_pedido");
            return this;
        }

        public Criteria andId_pedidoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_pedido >=", value, "id_pedido");
            return this;
        }

        public Criteria andId_pedidoLessThan(Long value) {
            addCriterion("id_pedido <", value, "id_pedido");
            return this;
        }

        public Criteria andId_pedidoLessThanOrEqualTo(Long value) {
            addCriterion("id_pedido <=", value, "id_pedido");
            return this;
        }

        public Criteria andId_pedidoIn(List<Long> values) {
            addCriterion("id_pedido in", values, "id_pedido");
            return this;
        }

        public Criteria andId_pedidoNotIn(List<Long> values) {
            addCriterion("id_pedido not in", values, "id_pedido");
            return this;
        }

        public Criteria andId_pedidoBetween(Long value1, Long value2) {
            addCriterion("id_pedido between", value1, value2, "id_pedido");
            return this;
        }

        public Criteria andId_pedidoNotBetween(Long value1, Long value2) {
            addCriterion("id_pedido not between", value1, value2, "id_pedido");
            return this;
        }

        public Criteria andFecha_entregaIsNull() {
            addCriterion("fecha_entrega is null");
            return this;
        }

        public Criteria andFecha_entregaIsNotNull() {
            addCriterion("fecha_entrega is not null");
            return this;
        }

        public Criteria andFecha_entregaEqualTo(Date value) {
            addCriterion("fecha_entrega =", value, "fecha_entrega");
            return this;
        }

        public Criteria andFecha_entregaNotEqualTo(Date value) {
            addCriterion("fecha_entrega <>", value, "fecha_entrega");
            return this;
        }

        public Criteria andFecha_entregaGreaterThan(Date value) {
            addCriterion("fecha_entrega >", value, "fecha_entrega");
            return this;
        }

        public Criteria andFecha_entregaGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha_entrega >=", value, "fecha_entrega");
            return this;
        }

        public Criteria andFecha_entregaLessThan(Date value) {
            addCriterion("fecha_entrega <", value, "fecha_entrega");
            return this;
        }

        public Criteria andFecha_entregaLessThanOrEqualTo(Date value) {
            addCriterion("fecha_entrega <=", value, "fecha_entrega");
            return this;
        }

        public Criteria andFecha_entregaIn(List<Date> values) {
            addCriterion("fecha_entrega in", values, "fecha_entrega");
            return this;
        }

        public Criteria andFecha_entregaNotIn(List<Date> values) {
            addCriterion("fecha_entrega not in", values, "fecha_entrega");
            return this;
        }

        public Criteria andFecha_entregaBetween(Date value1, Date value2) {
            addCriterion("fecha_entrega between", value1, value2, "fecha_entrega");
            return this;
        }

        public Criteria andFecha_entregaNotBetween(Date value1, Date value2) {
            addCriterion("fecha_entrega not between", value1, value2, "fecha_entrega");
            return this;
        }

        public Criteria andPODIsNull() {
            addCriterion("POD is null");
            return this;
        }

        public Criteria andPODIsNotNull() {
            addCriterion("POD is not null");
            return this;
        }

        public Criteria andPODEqualTo(String value) {
            addCriterion("POD =", value, "POD");
            return this;
        }

        public Criteria andPODNotEqualTo(String value) {
            addCriterion("POD <>", value, "POD");
            return this;
        }

        public Criteria andPODGreaterThan(String value) {
            addCriterion("POD >", value, "POD");
            return this;
        }

        public Criteria andPODGreaterThanOrEqualTo(String value) {
            addCriterion("POD >=", value, "POD");
            return this;
        }

        public Criteria andPODLessThan(String value) {
            addCriterion("POD <", value, "POD");
            return this;
        }

        public Criteria andPODLessThanOrEqualTo(String value) {
            addCriterion("POD <=", value, "POD");
            return this;
        }

        public Criteria andPODLike(String value) {
            addCriterion("POD like", value, "POD");
            return this;
        }

        public Criteria andPODNotLike(String value) {
            addCriterion("POD not like", value, "POD");
            return this;
        }

        public Criteria andPODIn(List<String> values) {
            addCriterion("POD in", values, "POD");
            return this;
        }

        public Criteria andPODNotIn(List<String> values) {
            addCriterion("POD not in", values, "POD");
            return this;
        }

        public Criteria andPODBetween(String value1, String value2) {
            addCriterion("POD between", value1, value2, "POD");
            return this;
        }

        public Criteria andPODNotBetween(String value1, String value2) {
            addCriterion("POD not between", value1, value2, "POD");
            return this;
        }

        public Criteria andComentariosIsNull() {
            addCriterion("comentarios is null");
            return this;
        }

        public Criteria andComentariosIsNotNull() {
            addCriterion("comentarios is not null");
            return this;
        }

        public Criteria andComentariosEqualTo(String value) {
            addCriterion("comentarios =", value, "comentarios");
            return this;
        }

        public Criteria andComentariosNotEqualTo(String value) {
            addCriterion("comentarios <>", value, "comentarios");
            return this;
        }

        public Criteria andComentariosGreaterThan(String value) {
            addCriterion("comentarios >", value, "comentarios");
            return this;
        }

        public Criteria andComentariosGreaterThanOrEqualTo(String value) {
            addCriterion("comentarios >=", value, "comentarios");
            return this;
        }

        public Criteria andComentariosLessThan(String value) {
            addCriterion("comentarios <", value, "comentarios");
            return this;
        }

        public Criteria andComentariosLessThanOrEqualTo(String value) {
            addCriterion("comentarios <=", value, "comentarios");
            return this;
        }

        public Criteria andComentariosLike(String value) {
            addCriterion("comentarios like", value, "comentarios");
            return this;
        }

        public Criteria andComentariosNotLike(String value) {
            addCriterion("comentarios not like", value, "comentarios");
            return this;
        }

        public Criteria andComentariosIn(List<String> values) {
            addCriterion("comentarios in", values, "comentarios");
            return this;
        }

        public Criteria andComentariosNotIn(List<String> values) {
            addCriterion("comentarios not in", values, "comentarios");
            return this;
        }

        public Criteria andComentariosBetween(String value1, String value2) {
            addCriterion("comentarios between", value1, value2, "comentarios");
            return this;
        }

        public Criteria andComentariosNotBetween(String value1, String value2) {
            addCriterion("comentarios not between", value1, value2, "comentarios");
            return this;
        }

        public Criteria andId_tipo_entregaIsNull() {
            addCriterion("id_tipo_entrega is null");
            return this;
        }

        public Criteria andId_tipo_entregaIsNotNull() {
            addCriterion("id_tipo_entrega is not null");
            return this;
        }

        public Criteria andId_tipo_entregaEqualTo(Long value) {
            addCriterion("id_tipo_entrega =", value, "id_tipo_entrega");
            return this;
        }

        public Criteria andId_tipo_entregaNotEqualTo(Long value) {
            addCriterion("id_tipo_entrega <>", value, "id_tipo_entrega");
            return this;
        }

        public Criteria andId_tipo_entregaGreaterThan(Long value) {
            addCriterion("id_tipo_entrega >", value, "id_tipo_entrega");
            return this;
        }

        public Criteria andId_tipo_entregaGreaterThanOrEqualTo(Long value) {
            addCriterion("id_tipo_entrega >=", value, "id_tipo_entrega");
            return this;
        }

        public Criteria andId_tipo_entregaLessThan(Long value) {
            addCriterion("id_tipo_entrega <", value, "id_tipo_entrega");
            return this;
        }

        public Criteria andId_tipo_entregaLessThanOrEqualTo(Long value) {
            addCriterion("id_tipo_entrega <=", value, "id_tipo_entrega");
            return this;
        }

        public Criteria andId_tipo_entregaIn(List<Long> values) {
            addCriterion("id_tipo_entrega in", values, "id_tipo_entrega");
            return this;
        }

        public Criteria andId_tipo_entregaNotIn(List<Long> values) {
            addCriterion("id_tipo_entrega not in", values, "id_tipo_entrega");
            return this;
        }

        public Criteria andId_tipo_entregaBetween(Long value1, Long value2) {
            addCriterion("id_tipo_entrega between", value1, value2, "id_tipo_entrega");
            return this;
        }

        public Criteria andId_tipo_entregaNotBetween(Long value1, Long value2) {
            addCriterion("id_tipo_entrega not between", value1, value2, "id_tipo_entrega");
            return this;
        }
    }
}