package com.proyectofinal.datos.dto;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProductoExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public ProductoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdProductoIsNull() {
            addCriterion("id_producto is null");
            return this;
        }

        public Criteria andIdProductoIsNotNull() {
            addCriterion("id_producto is not null");
            return this;
        }

        public Criteria andIdProductoEqualTo(Integer value) {
            addCriterion("id_producto =", value, "idProducto");
            return this;
        }

        public Criteria andIdProductoNotEqualTo(Integer value) {
            addCriterion("id_producto <>", value, "idProducto");
            return this;
        }

        public Criteria andIdProductoGreaterThan(Integer value) {
            addCriterion("id_producto >", value, "idProducto");
            return this;
        }

        public Criteria andIdProductoGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_producto >=", value, "idProducto");
            return this;
        }

        public Criteria andIdProductoLessThan(Integer value) {
            addCriterion("id_producto <", value, "idProducto");
            return this;
        }

        public Criteria andIdProductoLessThanOrEqualTo(Integer value) {
            addCriterion("id_producto <=", value, "idProducto");
            return this;
        }

        public Criteria andIdProductoIn(List<Integer> values) {
            addCriterion("id_producto in", values, "idProducto");
            return this;
        }

        public Criteria andIdProductoNotIn(List<Integer> values) {
            addCriterion("id_producto not in", values, "idProducto");
            return this;
        }

        public Criteria andIdProductoBetween(Integer value1, Integer value2) {
            addCriterion("id_producto between", value1, value2, "idProducto");
            return this;
        }

        public Criteria andIdProductoNotBetween(Integer value1, Integer value2) {
            addCriterion("id_producto not between", value1, value2, "idProducto");
            return this;
        }

        public Criteria andNombreIsNull() {
            addCriterion("nombre is null");
            return this;
        }

        public Criteria andNombreIsNotNull() {
            addCriterion("nombre is not null");
            return this;
        }

        public Criteria andNombreEqualTo(String value) {
            addCriterion("nombre =", value, "nombre");
            return this;
        }

        public Criteria andNombreNotEqualTo(String value) {
            addCriterion("nombre <>", value, "nombre");
            return this;
        }

        public Criteria andNombreGreaterThan(String value) {
            addCriterion("nombre >", value, "nombre");
            return this;
        }

        public Criteria andNombreGreaterThanOrEqualTo(String value) {
            addCriterion("nombre >=", value, "nombre");
            return this;
        }

        public Criteria andNombreLessThan(String value) {
            addCriterion("nombre <", value, "nombre");
            return this;
        }

        public Criteria andNombreLessThanOrEqualTo(String value) {
            addCriterion("nombre <=", value, "nombre");
            return this;
        }

        public Criteria andNombreLike(String value) {
            addCriterion("nombre like", value, "nombre");
            return this;
        }

        public Criteria andNombreNotLike(String value) {
            addCriterion("nombre not like", value, "nombre");
            return this;
        }

        public Criteria andNombreIn(List<String> values) {
            addCriterion("nombre in", values, "nombre");
            return this;
        }

        public Criteria andNombreNotIn(List<String> values) {
            addCriterion("nombre not in", values, "nombre");
            return this;
        }

        public Criteria andNombreBetween(String value1, String value2) {
            addCriterion("nombre between", value1, value2, "nombre");
            return this;
        }

        public Criteria andNombreNotBetween(String value1, String value2) {
            addCriterion("nombre not between", value1, value2, "nombre");
            return this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("descripcion is null");
            return this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("descripcion is not null");
            return this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("descripcion =", value, "descripcion");
            return this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("descripcion <>", value, "descripcion");
            return this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("descripcion >", value, "descripcion");
            return this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("descripcion >=", value, "descripcion");
            return this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("descripcion <", value, "descripcion");
            return this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("descripcion <=", value, "descripcion");
            return this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("descripcion like", value, "descripcion");
            return this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("descripcion not like", value, "descripcion");
            return this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("descripcion in", values, "descripcion");
            return this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("descripcion not in", values, "descripcion");
            return this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("descripcion between", value1, value2, "descripcion");
            return this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("descripcion not between", value1, value2, "descripcion");
            return this;
        }

        public Criteria andCodigoIsNull() {
            addCriterion("codigo is null");
            return this;
        }

        public Criteria andCodigoIsNotNull() {
            addCriterion("codigo is not null");
            return this;
        }

        public Criteria andCodigoEqualTo(String value) {
            addCriterion("codigo =", value, "codigo");
            return this;
        }

        public Criteria andCodigoNotEqualTo(String value) {
            addCriterion("codigo <>", value, "codigo");
            return this;
        }

        public Criteria andCodigoGreaterThan(String value) {
            addCriterion("codigo >", value, "codigo");
            return this;
        }

        public Criteria andCodigoGreaterThanOrEqualTo(String value) {
            addCriterion("codigo >=", value, "codigo");
            return this;
        }

        public Criteria andCodigoLessThan(String value) {
            addCriterion("codigo <", value, "codigo");
            return this;
        }

        public Criteria andCodigoLessThanOrEqualTo(String value) {
            addCriterion("codigo <=", value, "codigo");
            return this;
        }

        public Criteria andCodigoLike(String value) {
            addCriterion("codigo like", value, "codigo");
            return this;
        }

        public Criteria andCodigoNotLike(String value) {
            addCriterion("codigo not like", value, "codigo");
            return this;
        }

        public Criteria andCodigoIn(List<String> values) {
            addCriterion("codigo in", values, "codigo");
            return this;
        }

        public Criteria andCodigoNotIn(List<String> values) {
            addCriterion("codigo not in", values, "codigo");
            return this;
        }

        public Criteria andCodigoBetween(String value1, String value2) {
            addCriterion("codigo between", value1, value2, "codigo");
            return this;
        }

        public Criteria andCodigoNotBetween(String value1, String value2) {
            addCriterion("codigo not between", value1, value2, "codigo");
            return this;
        }

        public Criteria andImagenIsNull() {
            addCriterion("imagen is null");
            return this;
        }

        public Criteria andImagenIsNotNull() {
            addCriterion("imagen is not null");
            return this;
        }

        public Criteria andImagenEqualTo(String value) {
            addCriterion("imagen =", value, "imagen");
            return this;
        }

        public Criteria andImagenNotEqualTo(String value) {
            addCriterion("imagen <>", value, "imagen");
            return this;
        }

        public Criteria andImagenGreaterThan(String value) {
            addCriterion("imagen >", value, "imagen");
            return this;
        }

        public Criteria andImagenGreaterThanOrEqualTo(String value) {
            addCriterion("imagen >=", value, "imagen");
            return this;
        }

        public Criteria andImagenLessThan(String value) {
            addCriterion("imagen <", value, "imagen");
            return this;
        }

        public Criteria andImagenLessThanOrEqualTo(String value) {
            addCriterion("imagen <=", value, "imagen");
            return this;
        }

        public Criteria andImagenLike(String value) {
            addCriterion("imagen like", value, "imagen");
            return this;
        }

        public Criteria andImagenNotLike(String value) {
            addCriterion("imagen not like", value, "imagen");
            return this;
        }

        public Criteria andImagenIn(List<String> values) {
            addCriterion("imagen in", values, "imagen");
            return this;
        }

        public Criteria andImagenNotIn(List<String> values) {
            addCriterion("imagen not in", values, "imagen");
            return this;
        }

        public Criteria andImagenBetween(String value1, String value2) {
            addCriterion("imagen between", value1, value2, "imagen");
            return this;
        }

        public Criteria andImagenNotBetween(String value1, String value2) {
            addCriterion("imagen not between", value1, value2, "imagen");
            return this;
        }

        public Criteria andImagen_1IsNull() {
            addCriterion("imagen_1 is null");
            return this;
        }

        public Criteria andImagen_1IsNotNull() {
            addCriterion("imagen_1 is not null");
            return this;
        }

        public Criteria andImagen_1EqualTo(String value) {
            addCriterion("imagen_1 =", value, "imagen_1");
            return this;
        }

        public Criteria andImagen_1NotEqualTo(String value) {
            addCriterion("imagen_1 <>", value, "imagen_1");
            return this;
        }

        public Criteria andImagen_1GreaterThan(String value) {
            addCriterion("imagen_1 >", value, "imagen_1");
            return this;
        }

        public Criteria andImagen_1GreaterThanOrEqualTo(String value) {
            addCriterion("imagen_1 >=", value, "imagen_1");
            return this;
        }

        public Criteria andImagen_1LessThan(String value) {
            addCriterion("imagen_1 <", value, "imagen_1");
            return this;
        }

        public Criteria andImagen_1LessThanOrEqualTo(String value) {
            addCriterion("imagen_1 <=", value, "imagen_1");
            return this;
        }

        public Criteria andImagen_1Like(String value) {
            addCriterion("imagen_1 like", value, "imagen_1");
            return this;
        }

        public Criteria andImagen_1NotLike(String value) {
            addCriterion("imagen_1 not like", value, "imagen_1");
            return this;
        }

        public Criteria andImagen_1In(List<String> values) {
            addCriterion("imagen_1 in", values, "imagen_1");
            return this;
        }

        public Criteria andImagen_1NotIn(List<String> values) {
            addCriterion("imagen_1 not in", values, "imagen_1");
            return this;
        }

        public Criteria andImagen_1Between(String value1, String value2) {
            addCriterion("imagen_1 between", value1, value2, "imagen_1");
            return this;
        }

        public Criteria andImagen_1NotBetween(String value1, String value2) {
            addCriterion("imagen_1 not between", value1, value2, "imagen_1");
            return this;
        }

        public Criteria andImagen_2IsNull() {
            addCriterion("imagen_2 is null");
            return this;
        }

        public Criteria andImagen_2IsNotNull() {
            addCriterion("imagen_2 is not null");
            return this;
        }

        public Criteria andImagen_2EqualTo(String value) {
            addCriterion("imagen_2 =", value, "imagen_2");
            return this;
        }

        public Criteria andImagen_2NotEqualTo(String value) {
            addCriterion("imagen_2 <>", value, "imagen_2");
            return this;
        }

        public Criteria andImagen_2GreaterThan(String value) {
            addCriterion("imagen_2 >", value, "imagen_2");
            return this;
        }

        public Criteria andImagen_2GreaterThanOrEqualTo(String value) {
            addCriterion("imagen_2 >=", value, "imagen_2");
            return this;
        }

        public Criteria andImagen_2LessThan(String value) {
            addCriterion("imagen_2 <", value, "imagen_2");
            return this;
        }

        public Criteria andImagen_2LessThanOrEqualTo(String value) {
            addCriterion("imagen_2 <=", value, "imagen_2");
            return this;
        }

        public Criteria andImagen_2Like(String value) {
            addCriterion("imagen_2 like", value, "imagen_2");
            return this;
        }

        public Criteria andImagen_2NotLike(String value) {
            addCriterion("imagen_2 not like", value, "imagen_2");
            return this;
        }

        public Criteria andImagen_2In(List<String> values) {
            addCriterion("imagen_2 in", values, "imagen_2");
            return this;
        }

        public Criteria andImagen_2NotIn(List<String> values) {
            addCriterion("imagen_2 not in", values, "imagen_2");
            return this;
        }

        public Criteria andImagen_2Between(String value1, String value2) {
            addCriterion("imagen_2 between", value1, value2, "imagen_2");
            return this;
        }

        public Criteria andImagen_2NotBetween(String value1, String value2) {
            addCriterion("imagen_2 not between", value1, value2, "imagen_2");
            return this;
        }

        public Criteria andPrecioIsNull() {
            addCriterion("precio is null");
            return this;
        }

        public Criteria andPrecioIsNotNull() {
            addCriterion("precio is not null");
            return this;
        }

        public Criteria andPrecioEqualTo(Double value) {
            addCriterion("precio =", value, "precio");
            return this;
        }

        public Criteria andPrecioNotEqualTo(Double value) {
            addCriterion("precio <>", value, "precio");
            return this;
        }

        public Criteria andPrecioGreaterThan(Double value) {
            addCriterion("precio >", value, "precio");
            return this;
        }

        public Criteria andPrecioGreaterThanOrEqualTo(Double value) {
            addCriterion("precio >=", value, "precio");
            return this;
        }

        public Criteria andPrecioLessThan(Double value) {
            addCriterion("precio <", value, "precio");
            return this;
        }

        public Criteria andPrecioLessThanOrEqualTo(Double value) {
            addCriterion("precio <=", value, "precio");
            return this;
        }

        public Criteria andPrecioIn(List<Double> values) {
            addCriterion("precio in", values, "precio");
            return this;
        }

        public Criteria andPrecioNotIn(List<Double> values) {
            addCriterion("precio not in", values, "precio");
            return this;
        }

        public Criteria andPrecioBetween(Double value1, Double value2) {
            addCriterion("precio between", value1, value2, "precio");
            return this;
        }

        public Criteria andPrecioNotBetween(Double value1, Double value2) {
            addCriterion("precio not between", value1, value2, "precio");
            return this;
        }
    }
}