package com.proyectofinal.datos.dao;

import java.util.List;

import com.proyectofinal.datos.domain.Cliente;
import com.proyectofinal.datos.dto.ClienteExample;

public interface ClienteDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    int countByExample(ClienteExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    int deleteByPrimaryKey(Integer idCliente);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    Integer insert(Cliente record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    Integer insertSelective(Cliente record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    List<Cliente> selectByExample(ClienteExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    Cliente selectByPrimaryKey(Integer idCliente);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    int updateByPrimaryKeySelective(Cliente record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table clientes
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    int updateByPrimaryKey(Cliente record);
}