package com.proyectofinal.datos.dao;

import com.proyectofinal.datos.domain.Entrega;
import com.proyectofinal.datos.dto.EntregaExample;

import java.util.List;

public interface EntregaDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    int countByExample(EntregaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    int deleteByPrimaryKey(Integer idEntrega);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    Integer insert(Entrega record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    Integer insertSelective(Entrega record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    List<Entrega> selectByExample(EntregaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    Entrega selectByPrimaryKey(Integer idEntrega);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    int updateByExampleSelective(Entrega record, EntregaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    int updateByExample(Entrega record, EntregaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    int updateByPrimaryKeySelective(Entrega record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table entrega
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    int updateByPrimaryKey(Entrega record);
}