package com.proyectofinal.datos.dao;

import java.util.List;

import com.proyectofinal.datos.domain.EstadoPedido;
import com.proyectofinal.datos.dto.EstadoPedidoExample;
public interface EstadoPedidoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	int countByExample(EstadoPedidoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	int deleteByPrimaryKey(Integer idEstadoPedido);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	Integer insert(EstadoPedido record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	Integer insertSelective(EstadoPedido record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	List<EstadoPedido> selectByExample(EstadoPedidoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	EstadoPedido selectByPrimaryKey(Integer idEstadoPedido);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	int updateByExampleSelective(EstadoPedido record,
			EstadoPedidoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	int updateByExample(EstadoPedido record, EstadoPedidoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	int updateByPrimaryKeySelective(EstadoPedido record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table estado_pedidos
	 * @ibatorgenerated  Wed Oct 21 17:12:01 CDT 2015
	 */
	int updateByPrimaryKey(EstadoPedido record);
}