package com.proyectofinal.datos.dao;

import com.proyectofinal.datos.domain.Factura;
import com.proyectofinal.datos.dto.FacturaExample;

import java.util.List;

public interface FacturaDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facturas
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	int countByExample(FacturaExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facturas
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	int deleteByPrimaryKey(Integer idFactura);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facturas
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	Integer insert(Factura record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facturas
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	Integer insertSelective(Factura record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facturas
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	List<Factura> selectByExample(FacturaExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facturas
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	Factura selectByPrimaryKey(Integer idFactura);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facturas
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	int updateByExampleSelective(Factura record, FacturaExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facturas
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	int updateByExample(Factura record, FacturaExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facturas
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	int updateByPrimaryKeySelective(Factura record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facturas
	 * @ibatorgenerated  Thu Oct 22 16:39:02 CDT 2015
	 */
	int updateByPrimaryKey(Factura record);
}