package com.proyectofinal.datos.dao;

import com.proyectofinal.datos.domain.InstanciaProducto;
import com.proyectofinal.datos.dto.InstanciaProductoExample;

import java.util.List;

public interface InstanciaProductoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    int countByExample(InstanciaProductoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    int deleteByPrimaryKey(Integer idInstanciaProducto);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    Integer insert(InstanciaProducto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    Integer insertSelective(InstanciaProducto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    List<InstanciaProducto> selectByExample(InstanciaProductoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    InstanciaProducto selectByPrimaryKey(Integer idInstanciaProducto);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    int updateByExampleSelective(InstanciaProducto record, InstanciaProductoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    int updateByExample(InstanciaProducto record, InstanciaProductoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    int updateByPrimaryKeySelective(InstanciaProducto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table instancia_productos
     *
     * @ibatorgenerated Thu Oct 22 14:46:50 CDT 2015
     */
    int updateByPrimaryKey(InstanciaProducto record);
}