package com.proyectofinal.datos.dao;

import com.proyectofinal.datos.domain.Pedido;
import com.proyectofinal.datos.dto.PedidoExample;

import java.util.List;

public interface PedidoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    int countByExample(PedidoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    int deleteByPrimaryKey(Integer idPedido);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    Integer insert(Pedido record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    Integer insertSelective(Pedido record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    List<Pedido> selectByExample(PedidoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    Pedido selectByPrimaryKey(Integer idPedido);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    int updateByExampleSelective(Pedido record, PedidoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    int updateByExample(Pedido record, PedidoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    int updateByPrimaryKeySelective(Pedido record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pedidos
     *
     * @ibatorgenerated Thu Oct 22 16:15:00 CDT 2015
     */
    int updateByPrimaryKey(Pedido record);
}