package com.proyectofinal.datos.dao;

import java.util.List;

import com.proyectofinal.datos.domain.Producto;
import com.proyectofinal.datos.dto.ProductoExample;

public interface ProductoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    int countByExample(ProductoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    int deleteByPrimaryKey(Integer idProducto);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    Integer insert(Producto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    Integer insertSelective(Producto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    List<Producto> selectByExample(ProductoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    Producto selectByPrimaryKey(Integer idProducto);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    int updateByPrimaryKeySelective(Producto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table productos
     *
     * @ibatorgenerated Wed Oct 21 15:31:02 CDT 2015
     */
    int updateByPrimaryKey(Producto record);
}