package com.proyectofinal.datos.dao;

import com.proyectofinal.datos.domain.TipoPago;
import com.proyectofinal.datos.dto.TipoPagoExample;

import java.util.List;

public interface TipoPagoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    int countByExample(TipoPagoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    int deleteByPrimaryKey(Integer idTipoPago);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    Integer insert(TipoPago record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    Integer insertSelective(TipoPago record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    List<TipoPago> selectByExample(TipoPagoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    TipoPago selectByPrimaryKey(Integer idTipoPago);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    int updateByExampleSelective(TipoPago record, TipoPagoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    int updateByExample(TipoPago record, TipoPagoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    int updateByPrimaryKeySelective(TipoPago record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tipos_pago
     *
     * @ibatorgenerated Fri Oct 23 13:39:18 CDT 2015
     */
    int updateByPrimaryKey(TipoPago record);
}